// cspell:ignore Aldosivi Banfield Belgrano Godoy Lanús Sarsfield Atletico Mineiro Botafogo Chacopecoense Corinthians Cruzeiro Fluminense Gremio Internacional Palmeiras Santos Vasco Flamengo Sao Paulo Antofagasta Audax Italiano Deportes Iquique Huachipato O'Higgins Palestino San Luis Unión Española Concepción Católica Everton Universidad Petrolera Bucamaranga Tolima Medellín Jaguares Juniors Millonarios Caldas
export const teams = [
  { id: 1, name: "Aldosivi", country: "ARG" },
  { id: 2, name: "Argentinos Juniors", country: "ARG" },
  { id: 3, name: "Atlético Tucuman", country: "ARG" },
  { id: 4, name: "Banfield", country: "ARG" },
  { id: 5, name: "Belgrano", country: "ARG" },
  { id: 6, name: "Boca Juniors", country: "ARG" },
  { id: 7, name: "Colon", country: "ARG" },
  { id: 8, name: "Defensa y Justicia", country: "ARG" },
  { id: 9, name: "Estudiantes LP", country: "ARG" },
  { id: 10, name: "Gimnasia LP", country: "ARG" },
  { id: 11, name: "Godoy Cruz", country: "ARG" },
  { id: 12, name: "Huracán", country: "ARG" },
  { id: 13, name: "Independiente", country: "ARG" },
  { id: 14, name: "Lanús", country: "ARG" },
  { id: 15, name: "Newell's Old Boys", country: "ARG" },
  { id: 16, name: "Patronato", country: "ARG" },
  { id: 17, name: "Racing Club", country: "ARG" },
  { id: 18, name: "River Plate", country: "ARG" },
  { id: 19, name: "Rosario Central", country: "ARG" },
  { id: 20, name: "San Lorenzo", country: "ARG" },
  { id: 21, name: "San Martin de San Juan", country: "ARG" },
  { id: 22, name: "San Martin de Tucuman", country: "ARG" },
  { id: 23, name: "Talleres", country: "ARG" },
  { id: 24, name: "Tigre", country: "ARG" },
  { id: 25, name: "Unión", country: "ARG" },
  { id: 26, name: "Vélez Sarsfield", country: "ARG" },
  { id: 27, name: "Atletico Mineiro", country: "BRA" },
  { id: 29, name: "Botafogo", country: "BRA" },
  { id: 28, name: "Chacopecoense", country: "BRA" },
  { id: 30, name: "Corinthians", country: "BRA" },
  { id: 31, name: "Cruzeiro", country: "BRA" },
  { id: 32, name: "Flamengo", country: "BRA" },
  { id: 33, name: "Fluminense", country: "BRA" },
  { id: 34, name: "Gremio", country: "BRA" },
  { id: 35, name: "Internacional", country: "BRA" },
  { id: 36, name: "Palmeiras", country: "BRA" },
  { id: 37, name: "Santos", country: "BRA" },
  { id: 38, name: "São Paulo", country: "BRA" },
  { id: 39, name: "Vasco da Gama", country: "BRA" },
  { id: 40, name: "Antofagasta", country: "CHI" },
  { id: 41, name: "Audax Italiano", country: "CHI" },
  { id: 42, name: "Colo Colo", country: "CHI" },
  { id: 43, name: "Deportes Iquique", country: "CHI" },
  { id: 44, name: "Everton", country: "CHI" },
  { id: 45, name: "Huachipato", country: "CHI" },
  { id: 46, name: "O'Higgins", country: "CHI" },
  { id: 47, name: "Palestino", country: "CHI" },
  { id: 48, name: "San Luis", country: "CHI" },
  { id: 49, name: "Unión Española", country: "CHI" },
  { id: 50, name: "Universidad de Concepción", country: "CHI" },
  { id: 51, name: "Universidad Católica", country: "CHI" },
  { id: 52, name: "Universidad de Chile", country: "CHI" },
  { id: 53, name: "Alianza Petrolera", country: "COL" },
  { id: 54, name: "America de Cali", country: "COL" },
  { id: 55, name: "Atlético Bucamaranga", country: "COL" },
  { id: 56, name: "Atlético Nacional", country: "COL" },
  { id: 57, name: "Deportes Tolima", country: "COL" },
  { id: 58, name: "Deportivo Cali", country: "COL" },
  { id: 59, name: "Independiente Medellín", country: "COL" },
  { id: 60, name: "Jaguares de Cba", country: "COL" },
  { id: 61, name: "Juniors", country: "COL" },
  { id: 62, name: "Millonarios", country: "COL" },
  { id: 63, name: "Once Caldas", country: "COL" },
  { id: 64, name: "Santa Fe", country: "COL" },
  { id: 65, name: "Toronto", country: "Otros" },
  { id: 66, name: "Vancouver", country: "Otros" },
  { id: 67, name: "Alianza Lima", country: "Otros" },
  { id: 68, name: "Sporting Kansas", country: "Otros" },
  { id: 69, name: "Sporting Cristal", country: "Otros" },
  { id: 70, name: "New York Red Bulls", country: "Otros" },
  { id: 71, name: "LA Galaxy", country: "Otros" },
];
